site_name: SUBDENSE Dashboad
repo_url: https://github.com/subdense/dashboard/
site_url: https://subdense.github.io/dashboard/
theme:
  name: material
plugins:
  - search
markdown_extensions:
  - toc:
      permalink: "#"
      baselevel: 2
      separator: "_"
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
nav:
  - Home: index.md
  - Concepts: Concepts.md
  - Data:
    - Datasets: Datasets.md
    - Datasources: Datasources.md
  - Maps: 
    - Maps Overview: Maps/Maps.md
    - Strasbourg Variables: Maps/gridviz_plugin_strasbourg.html
  - Processes:
    - Processes: Processes/Processes.md
    - ComputeBuildingEvolution: Processes/ComputeBuildingEvolution.md
    - ComputeChangeInBuiltup_area: Processes/ComputeChangeInBuiltup_area.md
    - DeliminateStudyArea: Processes/DeliminateStudyArea.md
    - PrepareBuildingData: Processes/PrepareBuildingData.md
    - PrepareBuildingDataBDTopo: Processes/PrepareBuildingDataBDTopo.md
    - PrepareBuildingDataOSM: Processes/PrepareBuildingDataOSM.md
  - Studies:
    - StrasbourgStudy: StrasbourgStudy.md